# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: mommeet_development
  pool: 5
  username: dbuser
  password: dbpass

test:
  adapter: postgresql
  encoding: unicode
  database: mommeet_test
  pool: 5
  username: dbuser
  password: dbpass


production:
  adapter: postgresql
  encoding: unicode
  database: mommeet_production
  pool: 5
  username: 
  password: 
  host: localhost
  port: 5432